CREATE TABLE IF NOT EXISTS WALLETS (
    ID SERIAL PRIMARY KEY,
    FULL_NAME VARCHAR(100) NOT NULL,
    CPF BIGINT NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    "PASSWORD" VARCHAR(100) NOT NULL,
    "TYPE" INT NOT NULL,
    BALANCE DECIMAL(10, 2) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS cpf_idx ON WALLETS (CPF);

CREATE UNIQUE INDEX IF NOT EXISTS email_idx ON WALLETS (EMAIL);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID SERIAL PRIMARY KEY,
    PAYER INT NOT NULL,
    PAYEE INT NOT NULL,
    "VALUE" DECIMAL(10, 2) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    FOREIGN KEY (PAYER) REFERENCES WALLETS(ID),
    FOREIGN KEY (PAYEE) REFERENCES WALLETS(ID)
);